-- VQE InfiniQuantumSim query structure: monolithic_materialized
-- Generated by InferQ/generators/generate_query_structure_docs.py

WITH T0(i, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION))
), u_1(i,j, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9980475107000991 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.0624593178423802, -0.0), 
  (1, 0, 0.0624593178423802, 0.0), (1, 1, 0.9980475107000991, 0.0)
), u_2(i,j, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.992197667229329 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.12467473338522769, -0.0), 
  (1, 0, 0.12467473338522769, 0.0), (1, 1, 0.992197667229329, 0.0)
), cx(i,j,k,l, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), 
  (0, 1, 1, 1, 1.0, 0.0), 
  (1, 0, 1, 0, 1.0, 0.0), 
  (1, 1, 0, 1, 1.0, 0.0)
), u_3(i,j, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9689124217106447 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.24740395925452294, -0.0), 
  (1, 0, 0.24740395925452294, 0.0), (1, 1, 0.9689124217106447, 0.0)
), u_4(i,j, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9824733131012553 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.18640329676226988, -0.0), 
  (1, 0, 0.18640329676226988, 0.0), (1, 1, 0.9824733131012553, 0.0)
), u_5(i,j, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9515679480481722 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.30743851458038085, -0.0), 
  (1, 0, 0.30743851458038085, 0.0), (1, 1, 0.9515679480481722, 0.0)
), u_6(i,j, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9305076219123143 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.36627252908604757, -0.0), 
  (1, 0, 0.36627252908604757, 0.0), (1, 1, 0.9305076219123143, 0.0)
), K1 AS MATERIALIZED (
  SELECT u_1.i AS i, SUM(u_1.re * T0.re - u_1.im * T0.im) AS re, SUM(u_1.re * T0.im + u_1.im * T0.re) AS im FROM u_1, T0 WHERE u_1.j=T0.i GROUP BY u_1.i
), K2 AS MATERIALIZED (
  SELECT cx.i AS i, cx.j AS j, cx.l AS k, SUM(K1.re * cx.re - K1.im * cx.im) AS re, SUM(K1.re * cx.im + K1.im * cx.re) AS im FROM K1, cx WHERE K1.i=cx.k GROUP BY cx.i, cx.j, cx.l
), K3 AS MATERIALIZED (
  SELECT u_2.i AS i, SUM(u_2.re * T0.re - u_2.im * T0.im) AS re, SUM(u_2.re * T0.im + u_2.im * T0.re) AS im FROM u_2, T0 WHERE u_2.j=T0.i GROUP BY u_2.i
), K4 AS MATERIALIZED (
  SELECT K2.i AS i, K2.j AS j, SUM(K3.re * K2.re - K3.im * K2.im) AS re, SUM(K3.re * K2.im + K3.im * K2.re) AS im FROM K3, K2 WHERE K3.i=K2.k GROUP BY K2.i, K2.j
), K5 AS MATERIALIZED (
  SELECT u_4.i AS i, SUM(u_4.re * T0.re - u_4.im * T0.im) AS re, SUM(u_4.re * T0.im + u_4.im * T0.re) AS im FROM u_4, T0 WHERE u_4.j=T0.i GROUP BY u_4.i
), K6 AS MATERIALIZED (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, SUM(K5.re * cx.re - K5.im * cx.im) AS re, SUM(K5.re * cx.im + K5.im * cx.re) AS im FROM K5, cx WHERE K5.i=cx.l GROUP BY cx.i, cx.j, cx.k
), K7 AS MATERIALIZED (
  SELECT K4.j AS i, u_3.i AS j, SUM(K4.re * u_3.re - K4.im * u_3.im) AS re, SUM(K4.re * u_3.im + K4.im * u_3.re) AS im FROM K4, u_3 WHERE K4.i=u_3.j GROUP BY K4.j, u_3.i
), K8 AS MATERIALIZED (
  SELECT K6.j AS i, K6.k AS j, u_5.i AS k, SUM(K6.re * u_5.re - K6.im * u_5.im) AS re, SUM(K6.re * u_5.im + K6.im * u_5.re) AS im FROM K6, u_5 WHERE K6.i=u_5.j GROUP BY K6.j, K6.k, u_5.i
), K9 AS MATERIALIZED (
  SELECT K8.j AS i, K8.k AS j, u_6.i AS k, SUM(K8.re * u_6.re - K8.im * u_6.im) AS re, SUM(K8.re * u_6.im + K8.im * u_6.re) AS im FROM K8, u_6 WHERE K8.i=u_6.j GROUP BY K8.j, K8.k, u_6.i
) SELECT K7.j AS i, K9.j AS j, K9.k AS k, SUM(K9.re * K7.re - K9.im * K7.im) AS re, SUM(K9.re * K7.im + K9.im * K7.re) AS im FROM K9, K7 WHERE K9.i=K7.i GROUP BY K7.j, K9.j, K9.k ORDER BY i, j, k
