-- Graph State InfiniQuantumSim query structure: monolithic
-- Generated by tools/gen_query_docs.py

WITH T0(i, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION))
), u_1(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865476 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, 0.7071067811865475, -8.659560562354932e-17), 
  (1, 0, 0.7071067811865475, 0.0), (1, 1, -0.7071067811865476, 8.659560562354934e-17)
), cx(i,j,k,l, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), 
  (0, 1, 1, 1, 1.0, 0.0), 
  (1, 0, 1, 0, 1.0, 0.0), 
  (1, 1, 0, 1, 1.0, 0.0)
), u_2(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865476 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, 0.7071067811865475, -8.659560562354932e-17), 
  (1, 0, 0.7071067811865475, 0.0), (1, 1, -0.7071067811865476, 8.659560562354934e-17)
), u_3(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865476 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, 0.7071067811865475, -8.659560562354932e-17), 
  (1, 0, 0.7071067811865475, 0.0), (1, 1, -0.7071067811865476, 8.659560562354934e-17)
), K1 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, SUM(cx.re * T0.re - cx.im * T0.im) AS re, SUM(cx.re * T0.im + cx.im * T0.re) AS im FROM cx, T0 WHERE cx.l=T0.i GROUP BY cx.i, cx.j, cx.k
), K2 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, SUM(cx.re * T0.re - cx.im * T0.im) AS re, SUM(cx.re * T0.im + cx.im * T0.re) AS im FROM cx, T0 WHERE cx.l=T0.i GROUP BY cx.i, cx.j, cx.k
), K3 AS (
  SELECT u_1.i AS i, SUM(u_1.re * T0.re - u_1.im * T0.im) AS re, SUM(u_1.re * T0.im + u_1.im * T0.re) AS im FROM u_1, T0 WHERE u_1.j=T0.i GROUP BY u_1.i
), K4 AS (
  SELECT K1.i AS i, K1.j AS j, SUM(K3.re * K1.re - K3.im * K1.im) AS re, SUM(K3.re * K1.im + K3.im * K1.re) AS im FROM K3, K1 WHERE K3.i=K1.k GROUP BY K1.i, K1.j
), K5 AS (
  SELECT K2.i AS i, K2.k AS j, u_3.i AS k, SUM(K2.re * u_3.re - K2.im * u_3.im) AS re, SUM(K2.re * u_3.im + K2.im * u_3.re) AS im FROM K2, u_3 WHERE K2.j=u_3.j GROUP BY K2.i, K2.k, u_3.i
), K6 AS (
  SELECT K4.i AS i, u_2.i AS j, SUM(K4.re * u_2.re - K4.im * u_2.im) AS re, SUM(K4.re * u_2.im + K4.im * u_2.re) AS im FROM K4, u_2 WHERE K4.j=u_2.j GROUP BY K4.i, u_2.i
) SELECT K5.i AS i, K6.j AS j, K5.k AS k, SUM(K6.re * K5.re - K6.im * K5.im) AS re, SUM(K6.re * K5.im + K6.im * K5.re) AS im FROM K6, K5 WHERE K6.i=K5.j GROUP BY K5.i, K6.j, K5.k ORDER BY i, j, k
