-- Real Amplitudes InfiniQuantumSim query structure: monolithic
-- Generated by tools/gen_query_docs.py

WITH T0(i, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION))
), u_1(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9980475107000991 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.0624593178423802, -0.0), 
  (1, 0, 0.0624593178423802, 0.0), (1, 1, 0.9980475107000991, 0.0)
), u_2(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.992197667229329 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.12467473338522769, -0.0), 
  (1, 0, 0.12467473338522769, 0.0), (1, 1, 0.992197667229329, 0.0)
), u_3(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9824733131012553 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.18640329676226988, -0.0), 
  (1, 0, 0.18640329676226988, 0.0), (1, 1, 0.9824733131012553, 0.0)
), cx(i,j,k,l, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), 
  (0, 1, 1, 1, 1.0, 0.0), 
  (1, 0, 1, 0, 1.0, 0.0), 
  (1, 1, 0, 1, 1.0, 0.0)
), u_4(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9689124217106447 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.24740395925452294, -0.0), 
  (1, 0, 0.24740395925452294, 0.0), (1, 1, 0.9689124217106447, 0.0)
), u_5(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9515679480481722 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.30743851458038085, -0.0), 
  (1, 0, 0.30743851458038085, 0.0), (1, 1, 0.9515679480481722, 0.0)
), u_6(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9305076219123143 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.36627252908604757, -0.0), 
  (1, 0, 0.36627252908604757, 0.0), (1, 1, 0.9305076219123143, 0.0)
), K1 AS (
  SELECT u_1.i AS i, SUM(u_1.re * T0.re - u_1.im * T0.im) AS re, SUM(u_1.re * T0.im + u_1.im * T0.re) AS im FROM u_1, T0 WHERE u_1.j=T0.i GROUP BY u_1.i
), K2 AS (
  SELECT cx.i AS i, cx.j AS j, cx.l AS k, SUM(K1.re * cx.re - K1.im * cx.im) AS re, SUM(K1.re * cx.im + K1.im * cx.re) AS im FROM K1, cx WHERE K1.i=cx.k GROUP BY cx.i, cx.j, cx.l
), K3 AS (
  SELECT u_2.i AS i, SUM(u_2.re * T0.re - u_2.im * T0.im) AS re, SUM(u_2.re * T0.im + u_2.im * T0.re) AS im FROM u_2, T0 WHERE u_2.j=T0.i GROUP BY u_2.i
), K4 AS (
  SELECT cx.i AS i, cx.j AS j, cx.l AS k, SUM(K3.re * cx.re - K3.im * cx.im) AS re, SUM(K3.re * cx.im + K3.im * cx.re) AS im FROM K3, cx WHERE K3.i=cx.k GROUP BY cx.i, cx.j, cx.l
), K5 AS (
  SELECT u_3.i AS i, SUM(u_3.re * T0.re - u_3.im * T0.im) AS re, SUM(u_3.re * T0.im + u_3.im * T0.re) AS im FROM u_3, T0 WHERE u_3.j=T0.i GROUP BY u_3.i
), K6 AS (
  SELECT K4.i AS i, K4.j AS j, SUM(K5.re * K4.re - K5.im * K4.im) AS re, SUM(K5.re * K4.im + K5.im * K4.re) AS im FROM K5, K4 WHERE K5.i=K4.k GROUP BY K4.i, K4.j
), K7 AS (
  SELECT K2.j AS i, K2.k AS j, u_4.i AS k, SUM(K2.re * u_4.re - K2.im * u_4.im) AS re, SUM(K2.re * u_4.im + K2.im * u_4.re) AS im FROM K2, u_4 WHERE K2.i=u_4.j GROUP BY K2.j, K2.k, u_4.i
), K8 AS (
  SELECT K6.i AS i, u_6.i AS j, SUM(K6.re * u_6.re - K6.im * u_6.im) AS re, SUM(K6.re * u_6.im + K6.im * u_6.re) AS im FROM K6, u_6 WHERE K6.j=u_6.j GROUP BY K6.i, u_6.i
), K9 AS (
  SELECT K7.j AS i, K7.k AS j, u_5.i AS k, SUM(K7.re * u_5.re - K7.im * u_5.im) AS re, SUM(K7.re * u_5.im + K7.im * u_5.re) AS im FROM K7, u_5 WHERE K7.i=u_5.j GROUP BY K7.j, K7.k, u_5.i
) SELECT K9.j AS i, K9.k AS j, K8.j AS k, SUM(K9.re * K8.re - K9.im * K8.im) AS re, SUM(K9.re * K8.im + K9.im * K8.re) AS im FROM K9, K8 WHERE K9.i=K8.i GROUP BY K9.j, K9.k, K8.j ORDER BY i, j, k
