-- Quantum Walk InfiniQuantumSim query structure: monolithic
-- Generated by tools/gen_query_docs.py

WITH T0(i, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION))
), u_1(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865476 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, 0.7071067811865475, -8.659560562354932e-17), 
  (1, 0, 0.7071067811865475, 0.0), (1, 1, -0.7071067811865476, 8.659560562354934e-17)
), cx(i,j,k,l, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), 
  (0, 1, 1, 1, 1.0, 0.0), 
  (1, 0, 1, 0, 1.0, 0.0), 
  (1, 1, 0, 1, 1.0, 0.0)
), rz_1(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9238795325112867 AS DOUBLE PRECISION), CAST(0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 1, 0.9238795325112867, -0.3826834323650898)
), rz_2(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9238795325112867 AS DOUBLE PRECISION), CAST(-0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 1, 0.9238795325112867, 0.3826834323650898)
), rz_3(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9238795325112867 AS DOUBLE PRECISION), CAST(0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 1, 0.9238795325112867, -0.3826834323650898)
), rz_4(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9238795325112867 AS DOUBLE PRECISION), CAST(-0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 1, 0.9238795325112867, 0.3826834323650898)
), u_2(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), 
  (1, 1, 0.7071067811865472, 0.7071067811865478)
), u_3(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(1 AS INTEGER), CAST(-0.9238795325112867 AS DOUBLE PRECISION), CAST(0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 0, -0.9238795325112867, -0.3826834323650899)
), rz_5(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9238795325112867 AS DOUBLE PRECISION), CAST(0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 1, 0.9238795325112867, -0.3826834323650898)
), u_4(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(1 AS INTEGER), CAST(-0.9238795325112867 AS DOUBLE PRECISION), CAST(-0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 0, -0.9238795325112865, 0.3826834323650903)
), rz_6(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9238795325112867 AS DOUBLE PRECISION), CAST(-0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 1, 0.9238795325112867, 0.3826834323650898)
), rz_7(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9238795325112867 AS DOUBLE PRECISION), CAST(0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 1, 0.9238795325112867, -0.3826834323650898)
), rz_8(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9238795325112867 AS DOUBLE PRECISION), CAST(-0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 1, 0.9238795325112867, 0.3826834323650898)
), u_5(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865477 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, 0.4999999999999999, 0.5), 
  (1, 0, 0.7071067811865475, 0.0), (1, 1, -0.5000000000000001, -0.5000000000000001)
), u_6(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(1 AS INTEGER), CAST(-0.9238795325112867 AS DOUBLE PRECISION), CAST(0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 0, -0.9238795325112867, -0.3826834323650899)
), u_7(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(1 AS INTEGER), CAST(-0.9238795325112867 AS DOUBLE PRECISION), CAST(-0.3826834323650898 AS DOUBLE PRECISION)), 
  (1, 0, -0.9238795325112865, 0.3826834323650903)
), K1 AS (
  SELECT cx.i AS i, cx.j AS j, cx.l AS k, SUM(cx.re * T0.re - cx.im * T0.im) AS re, SUM(cx.re * T0.im + cx.im * T0.re) AS im FROM cx, T0 WHERE cx.k=T0.i GROUP BY cx.i, cx.j, cx.l
), K2 AS (
  SELECT cx.i AS i, cx.j AS j, cx.l AS k, SUM(cx.re * T0.re - cx.im * T0.im) AS re, SUM(cx.re * T0.im + cx.im * T0.re) AS im FROM cx, T0 WHERE cx.k=T0.i GROUP BY cx.i, cx.j, cx.l
), K3 AS (
  SELECT u_1.i AS i, SUM(u_1.re * T0.re - u_1.im * T0.im) AS re, SUM(u_1.re * T0.im + u_1.im * T0.re) AS im FROM u_1, T0 WHERE u_1.j=T0.i GROUP BY u_1.i
), K4 AS (
  SELECT K1.i AS i, K1.j AS j, SUM(K3.re * K1.re - K3.im * K1.im) AS re, SUM(K3.re * K1.im + K3.im * K1.re) AS im FROM K3, K1 WHERE K3.i=K1.k GROUP BY K1.i, K1.j
), K5 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, rz_2.j AS l, SUM(cx.re * rz_2.re - cx.im * rz_2.im) AS re, SUM(cx.re * rz_2.im + cx.im * rz_2.re) AS im FROM cx, rz_2 WHERE cx.l=rz_2.i GROUP BY cx.i, cx.j, cx.k, rz_2.j
), K6 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, rz_3.j AS l, SUM(cx.re * rz_3.re - cx.im * rz_3.im) AS re, SUM(cx.re * rz_3.im + cx.im * rz_3.re) AS im FROM cx, rz_3 WHERE cx.l=rz_3.i GROUP BY cx.i, cx.j, cx.k, rz_3.j
), K7 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, rz_4.j AS l, SUM(cx.re * rz_4.re - cx.im * rz_4.im) AS re, SUM(cx.re * rz_4.im + cx.im * rz_4.re) AS im FROM cx, rz_4 WHERE cx.l=rz_4.i GROUP BY cx.i, cx.j, cx.k, rz_4.j
), K8 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, u_2.j AS l, SUM(cx.re * u_2.re - cx.im * u_2.im) AS re, SUM(cx.re * u_2.im + cx.im * u_2.re) AS im FROM cx, u_2 WHERE cx.l=u_2.i GROUP BY cx.i, cx.j, cx.k, u_2.j
), K9 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, rz_5.j AS l, SUM(cx.re * rz_5.re - cx.im * rz_5.im) AS re, SUM(cx.re * rz_5.im + cx.im * rz_5.re) AS im FROM cx, rz_5 WHERE cx.l=rz_5.i GROUP BY cx.i, cx.j, cx.k, rz_5.j
), K10 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, rz_6.j AS l, SUM(cx.re * rz_6.re - cx.im * rz_6.im) AS re, SUM(cx.re * rz_6.im + cx.im * rz_6.re) AS im FROM cx, rz_6 WHERE cx.l=rz_6.i GROUP BY cx.i, cx.j, cx.k, rz_6.j
), K11 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, rz_7.j AS l, SUM(cx.re * rz_7.re - cx.im * rz_7.im) AS re, SUM(cx.re * rz_7.im + cx.im * rz_7.re) AS im FROM cx, rz_7 WHERE cx.l=rz_7.i GROUP BY cx.i, cx.j, cx.k, rz_7.j
), K12 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, rz_8.j AS l, SUM(cx.re * rz_8.re - cx.im * rz_8.im) AS re, SUM(cx.re * rz_8.im + cx.im * rz_8.re) AS im FROM cx, rz_8 WHERE cx.l=rz_8.i GROUP BY cx.i, cx.j, cx.k, rz_8.j
), K13 AS (
  SELECT K2.i AS i, K2.j AS j, rz_1.j AS k, SUM(K2.re * rz_1.re - K2.im * rz_1.im) AS re, SUM(K2.re * rz_1.im + K2.im * rz_1.re) AS im FROM K2, rz_1 WHERE K2.k=rz_1.i GROUP BY K2.i, K2.j, rz_1.j
), K14 AS (
  SELECT K7.i AS i, K7.k AS j, K7.l AS k, u_3.i AS l, SUM(K7.re * u_3.re - K7.im * u_3.im) AS re, SUM(K7.re * u_3.im + K7.im * u_3.re) AS im FROM K7, u_3 WHERE K7.j=u_3.j GROUP BY K7.i, K7.k, K7.l, u_3.i
), K15 AS (
  SELECT K9.i AS i, K9.j AS j, K9.l AS k, u_4.j AS l, SUM(K9.re * u_4.re - K9.im * u_4.im) AS re, SUM(K9.re * u_4.im + K9.im * u_4.re) AS im FROM K9, u_4 WHERE K9.k=u_4.i GROUP BY K9.i, K9.j, K9.l, u_4.j
), K16 AS (
  SELECT K11.i AS i, K11.k AS j, K11.l AS k, u_5.i AS l, SUM(K11.re * u_5.re - K11.im * u_5.im) AS re, SUM(K11.re * u_5.im + K11.im * u_5.re) AS im FROM K11, u_5 WHERE K11.j=u_5.j GROUP BY K11.i, K11.k, K11.l, u_5.i
), K17 AS (
  SELECT K12.i AS i, K12.k AS j, K12.l AS k, u_6.i AS l, SUM(K12.re * u_6.re - K12.im * u_6.im) AS re, SUM(K12.re * u_6.im + K12.im * u_6.re) AS im FROM K12, u_6 WHERE K12.j=u_6.j GROUP BY K12.i, K12.k, K12.l, u_6.i
), K18 AS (
  SELECT K13.i AS i, K13.j AS j, K4.i AS k, SUM(K13.re * K4.re - K13.im * K4.im) AS re, SUM(K13.re * K4.im + K13.im * K4.re) AS im FROM K13, K4 WHERE K13.k=K4.j GROUP BY K13.i, K13.j, K4.i
), K19 AS (
  SELECT K18.i AS i, K5.i AS j, K5.j AS k, SUM(K18.re * K5.re - K18.im * K5.im) AS re, SUM(K18.re * K5.im + K18.im * K5.re) AS im FROM K18, K5 WHERE K18.j=K5.l AND K18.k=K5.k GROUP BY K18.i, K5.i, K5.j
), K20 AS (
  SELECT K19.j AS i, K6.i AS j, K6.j AS k, SUM(K19.re * K6.re - K19.im * K6.im) AS re, SUM(K19.re * K6.im + K19.im * K6.re) AS im FROM K19, K6 WHERE K19.i=K6.k AND K19.k=K6.l GROUP BY K19.j, K6.i, K6.j
), K21 AS (
  SELECT K20.k AS i, K14.i AS j, K14.l AS k, SUM(K20.re * K14.re - K20.im * K14.im) AS re, SUM(K20.re * K14.im + K20.im * K14.re) AS im FROM K20, K14 WHERE K20.i=K14.k AND K20.j=K14.j GROUP BY K20.k, K14.i, K14.l
), K22 AS (
  SELECT K21.j AS i, K8.i AS j, K8.j AS k, SUM(K21.re * K8.re - K21.im * K8.im) AS re, SUM(K21.re * K8.im + K21.im * K8.re) AS im FROM K21, K8 WHERE K21.i=K8.l AND K21.k=K8.k GROUP BY K21.j, K8.i, K8.j
), K23 AS (
  SELECT K22.j AS i, K15.i AS j, K15.j AS k, SUM(K22.re * K15.re - K22.im * K15.im) AS re, SUM(K22.re * K15.im + K22.im * K15.re) AS im FROM K22, K15 WHERE K22.i=K15.l AND K22.k=K15.k GROUP BY K22.j, K15.i, K15.j
), K24 AS (
  SELECT K23.j AS i, K10.i AS j, K10.j AS k, SUM(K23.re * K10.re - K23.im * K10.im) AS re, SUM(K23.re * K10.im + K23.im * K10.re) AS im FROM K23, K10 WHERE K23.i=K10.k AND K23.k=K10.l GROUP BY K23.j, K10.i, K10.j
), K25 AS (
  SELECT K24.j AS i, K16.i AS j, K16.l AS k, SUM(K24.re * K16.re - K24.im * K16.im) AS re, SUM(K24.re * K16.im + K24.im * K16.re) AS im FROM K24, K16 WHERE K24.i=K16.j AND K24.k=K16.k GROUP BY K24.j, K16.i, K16.l
), K26 AS (
  SELECT K25.k AS i, K17.i AS j, K17.l AS k, SUM(K25.re * K17.re - K25.im * K17.im) AS re, SUM(K25.re * K17.im + K25.im * K17.re) AS im FROM K25, K17 WHERE K25.i=K17.k AND K25.j=K17.j GROUP BY K25.k, K17.i, K17.l
) SELECT K26.i AS i, K26.k AS j, u_7.i AS k, SUM(K26.re * u_7.re - K26.im * u_7.im) AS re, SUM(K26.re * u_7.im + K26.im * u_7.re) AS im FROM K26, u_7 WHERE K26.j=u_7.j GROUP BY K26.i, K26.k, u_7.i ORDER BY i, j, k
