-- QPE InfiniQuantumSim query structure: monolithic
-- Generated by tools/gen_query_docs.py

WITH T0(i, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION))
), u_1(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865476 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, 0.7071067811865475, -8.659560562354932e-17), 
  (1, 0, 0.7071067811865475, 0.0), (1, 1, -0.7071067811865476, 8.659560562354934e-17)
), u_2(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865475 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.7071067811865476, -0.0), 
  (1, 0, -0.3583947274114282, 0.6095516543851621), (1, 1, -0.35839472741142814, 0.6095516543851621)
), x(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(1 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), 
  (1, 0, 1.0, 0.0)
), cx(i,j,k,l, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), 
  (0, 1, 1, 1, 1.0, 0.0), 
  (1, 0, 1, 0, 1.0, 0.0), 
  (1, 1, 0, 1, 1.0, 0.0)
), rz_1(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.9238795325112867 AS DOUBLE PRECISION), CAST(0.3826834323650897 AS DOUBLE PRECISION)), 
  (1, 1, 0.9238795325112867, -0.3826834323650897)
), u_3(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865476 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, 0.7071067811865475, -8.659560562354932e-17), 
  (1, 0, 0.7071067811865475, 0.0), (1, 1, -0.7071067811865476, 8.659560562354934e-17)
), u_4(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865477 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.547913351298253, -0.4469798199797359), 
  (1, 0, -0.7071067811865475, -8.659560562354932e-17), (1, 1, -0.5479133512982531, -0.44697981997973607)
), u_5(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(1 AS INTEGER), CAST(0.24037222675775302 AS DOUBLE PRECISION), CAST(-0.9706807882118196 AS DOUBLE PRECISION)), 
  (1, 0, 0.011125776665166705, 0.9999381066314039)
), u_6(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), 
  (1, 1, 0.7071067811865476, 0.7071067811865475)
), u_7(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), 
  (1, 1, 0.7071067811865476, -0.7071067811865475)
), u_8(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865476 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, 0.7071067811865475, -8.659560562354932e-17), 
  (1, 0, 0.7071067811865475, 0.0), (1, 1, -0.7071067811865476, 8.659560562354934e-17)
), u_9(i,j, re, im) AS (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865476 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, -0.7071067811865475, -0.0), 
  (1, 0, 0.7034957079668553, 0.07137078444442697), (1, 1, 0.7034957079668555, 0.07137078444442699)
), K1 AS (
  SELECT u_1.i AS i, SUM(u_1.re * T0.re - u_1.im * T0.im) AS re, SUM(u_1.re * T0.im + u_1.im * T0.re) AS im FROM u_1, T0 WHERE u_1.j=T0.i GROUP BY u_1.i
), K2 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, SUM(K1.re * cx.re - K1.im * cx.im) AS re, SUM(K1.re * cx.im + K1.im * cx.re) AS im FROM K1, cx WHERE K1.i=cx.l GROUP BY cx.i, cx.j, cx.k
), K3 AS (
  SELECT u_2.i AS i, SUM(u_2.re * T0.re - u_2.im * T0.im) AS re, SUM(u_2.re * T0.im + u_2.im * T0.re) AS im FROM u_2, T0 WHERE u_2.j=T0.i GROUP BY u_2.i
), K4 AS (
  SELECT cx.i AS i, cx.j AS j, cx.l AS k, SUM(K3.re * cx.re - K3.im * cx.im) AS re, SUM(K3.re * cx.im + K3.im * cx.re) AS im FROM K3, cx WHERE K3.i=cx.k GROUP BY cx.i, cx.j, cx.l
), K5 AS (
  SELECT x.i AS i, SUM(x.re * T0.re - x.im * T0.im) AS re, SUM(x.re * T0.im + x.im * T0.re) AS im FROM x, T0 WHERE x.j=T0.i GROUP BY x.i
), K6 AS (
  SELECT K2.i AS i, K2.j AS j, SUM(K5.re * K2.re - K5.im * K2.im) AS re, SUM(K5.re * K2.im + K5.im * K2.re) AS im FROM K5, K2 WHERE K5.i=K2.k GROUP BY K2.i, K2.j
), K7 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, rz_1.j AS l, SUM(cx.re * rz_1.re - cx.im * rz_1.im) AS re, SUM(cx.re * rz_1.im + cx.im * rz_1.re) AS im FROM cx, rz_1 WHERE cx.l=rz_1.i GROUP BY cx.i, cx.j, cx.k, rz_1.j
), K8 AS (
  SELECT K7.i AS i, K7.j AS j, SUM(K7.re * K6.re - K7.im * K6.im) AS re, SUM(K7.re * K6.im + K7.im * K6.re) AS im FROM K7, K6 WHERE K7.k=K6.i AND K7.l=K6.j GROUP BY K7.i, K7.j
), K9 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, u_3.j AS l, SUM(cx.re * u_3.re - cx.im * u_3.im) AS re, SUM(cx.re * u_3.im + cx.im * u_3.re) AS im FROM cx, u_3 WHERE cx.l=u_3.i GROUP BY cx.i, cx.j, cx.k, u_3.j
), K10 AS (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, u_6.j AS l, SUM(cx.re * u_6.re - cx.im * u_6.im) AS re, SUM(cx.re * u_6.im + cx.im * u_6.re) AS im FROM cx, u_6 WHERE cx.l=u_6.i GROUP BY cx.i, cx.j, cx.k, u_6.j
), K11 AS (
  SELECT K10.i AS i, K10.j AS j, K9.k AS k, K9.l AS l, SUM(K10.re * K9.re - K10.im * K9.im) AS re, SUM(K10.re * K9.im + K10.im * K9.re) AS im FROM K10, K9 WHERE K10.k=K9.i AND K10.l=K9.j GROUP BY K10.i, K10.j, K9.k, K9.l
), K12 AS (
  SELECT K4.i AS i, K4.j AS j, u_4.j AS k, SUM(K4.re * u_4.re - K4.im * u_4.im) AS re, SUM(K4.re * u_4.im + K4.im * u_4.re) AS im FROM K4, u_4 WHERE K4.k=u_4.i GROUP BY K4.i, K4.j, u_4.j
), K13 AS (
  SELECT K11.i AS i, K11.j AS j, K11.l AS k, u_5.j AS l, SUM(K11.re * u_5.re - K11.im * u_5.im) AS re, SUM(K11.re * u_5.im + K11.im * u_5.re) AS im FROM K11, u_5 WHERE K11.k=u_5.i GROUP BY K11.i, K11.j, K11.l, u_5.j
), K14 AS (
  SELECT K13.i AS i, K13.k AS j, K13.l AS k, u_7.i AS l, SUM(K13.re * u_7.re - K13.im * u_7.im) AS re, SUM(K13.re * u_7.im + K13.im * u_7.re) AS im FROM K13, u_7 WHERE K13.j=u_7.j GROUP BY K13.i, K13.k, K13.l, u_7.i
), K15 AS (
  SELECT K14.j AS i, K14.k AS j, K14.l AS k, u_8.i AS l, SUM(K14.re * u_8.re - K14.im * u_8.im) AS re, SUM(K14.re * u_8.im + K14.im * u_8.re) AS im FROM K14, u_8 WHERE K14.i=u_8.j GROUP BY K14.j, K14.k, K14.l, u_8.i
), K16 AS (
  SELECT K15.j AS i, K15.k AS j, K15.l AS k, K8.i AS l, SUM(K15.re * K8.re - K15.im * K8.im) AS re, SUM(K15.re * K8.im + K15.im * K8.re) AS im FROM K15, K8 WHERE K15.i=K8.j GROUP BY K15.j, K15.k, K15.l, K8.i
), K17 AS (
  SELECT K16.j AS i, K16.k AS j, K12.j AS k, SUM(K16.re * K12.re - K16.im * K12.im) AS re, SUM(K16.re * K12.im + K16.im * K12.re) AS im FROM K16, K12 WHERE K16.i=K12.i AND K16.l=K12.k GROUP BY K16.j, K16.k, K12.j
) SELECT K17.i AS i, K17.j AS j, u_9.i AS k, SUM(K17.re * u_9.re - K17.im * u_9.im) AS re, SUM(K17.re * u_9.im + K17.im * u_9.re) AS im FROM K17, u_9 WHERE K17.k=u_9.j GROUP BY K17.i, K17.j, u_9.i ORDER BY i, j, k
