-- GHZ State InfiniQuantumSim query structure: monolithic_materialized
-- Generated by tools/gen_query_docs.py

WITH T0(i, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION))
), u_1(i,j, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0.7071067811865476 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), (0, 1, 0.7071067811865475, -8.659560562354932e-17), 
  (1, 0, 0.7071067811865475, 0.0), (1, 1, -0.7071067811865476, 8.659560562354934e-17)
), cx(i,j,k,l, re, im) AS MATERIALIZED (
  VALUES (CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(0 AS INTEGER), CAST(1.0 AS DOUBLE PRECISION), CAST(0.0 AS DOUBLE PRECISION)), 
  (0, 1, 1, 1, 1.0, 0.0), 
  (1, 0, 1, 0, 1.0, 0.0), 
  (1, 1, 0, 1, 1.0, 0.0)
), K1 AS MATERIALIZED (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, SUM(cx.re * T0.re - cx.im * T0.im) AS re, SUM(cx.re * T0.im + cx.im * T0.re) AS im FROM cx, T0 WHERE cx.l=T0.i GROUP BY cx.i, cx.j, cx.k
), K2 AS MATERIALIZED (
  SELECT cx.i AS i, cx.j AS j, cx.k AS k, SUM(cx.re * T0.re - cx.im * T0.im) AS re, SUM(cx.re * T0.im + cx.im * T0.re) AS im FROM cx, T0 WHERE cx.l=T0.i GROUP BY cx.i, cx.j, cx.k
), K3 AS MATERIALIZED (
  SELECT u_1.i AS i, SUM(u_1.re * T0.re - u_1.im * T0.im) AS re, SUM(u_1.re * T0.im + u_1.im * T0.re) AS im FROM u_1, T0 WHERE u_1.j=T0.i GROUP BY u_1.i
), K4 AS MATERIALIZED (
  SELECT K1.i AS i, K1.j AS j, SUM(K3.re * K1.re - K3.im * K1.im) AS re, SUM(K3.re * K1.im + K3.im * K1.re) AS im FROM K3, K1 WHERE K3.i=K1.k GROUP BY K1.i, K1.j
) SELECT K4.i AS i, K2.i AS j, K2.j AS k, SUM(K4.re * K2.re - K4.im * K2.im) AS re, SUM(K4.re * K2.im + K4.im * K2.re) AS im FROM K4, K2 WHERE K4.j=K2.k GROUP BY K4.i, K2.i, K2.j ORDER BY i, j, k
